"use client";
import { useState, useEffect, useCallback } from "react";
import { MusicTrack } from "@/lib/musicSearch";

// A persistent music library so the user doesn't have to re-search every time.
// Two collections, both in localStorage:
//   • saved   — individual bookmarked tracks (the "Liked songs")
//   • playlists — named ordered lists of tracks (incl. AI-generated ones)
const KEY = "radiofr_song_library_v1";

export interface Playlist {
  id: string;
  name: string;
  createdAt: number;
  ai?: boolean;        // true when generated by the auto-playlist feature
  tracks: MusicTrack[];
}

interface LibraryData {
  saved: MusicTrack[];
  playlists: Playlist[];
}

const EMPTY: LibraryData = { saved: [], playlists: [] };

function load(): LibraryData {
  try {
    const raw = localStorage.getItem(KEY);
    if (!raw) return EMPTY;
    const d = JSON.parse(raw);
    return { saved: d.saved ?? [], playlists: d.playlists ?? [] };
  } catch {
    return EMPTY;
  }
}

export function useSongLibrary() {
  const [data, setData] = useState<LibraryData>(EMPTY);

  useEffect(() => { setData(load()); }, []);

  const persist = useCallback((next: LibraryData) => {
    setData(next);
    try { localStorage.setItem(KEY, JSON.stringify(next)); } catch {}
  }, []);

  const isSaved = useCallback((id: string) => data.saved.some((t) => t.id === id), [data.saved]);

  const toggleSaved = useCallback((track: MusicTrack) => {
    setData((prev) => {
      const exists = prev.saved.some((t) => t.id === track.id);
      const saved = exists ? prev.saved.filter((t) => t.id !== track.id) : [track, ...prev.saved];
      const next = { ...prev, saved };
      try { localStorage.setItem(KEY, JSON.stringify(next)); } catch {}
      return next;
    });
  }, []);

  const createPlaylist = useCallback((name: string, tracks: MusicTrack[] = [], ai = false): string => {
    const id = `pl_${Math.random().toString(36).slice(2)}_${Date.now()}`;
    setData((prev) => {
      const next = {
        ...prev,
        playlists: [{ id, name, createdAt: Date.now(), ai, tracks }, ...prev.playlists],
      };
      try { localStorage.setItem(KEY, JSON.stringify(next)); } catch {}
      return next;
    });
    return id;
  }, []);

  const deletePlaylist = useCallback((id: string) => {
    setData((prev) => {
      const next = { ...prev, playlists: prev.playlists.filter((p) => p.id !== id) };
      try { localStorage.setItem(KEY, JSON.stringify(next)); } catch {}
      return next;
    });
  }, []);

  const addToPlaylist = useCallback((id: string, track: MusicTrack) => {
    setData((prev) => {
      const playlists = prev.playlists.map((p) =>
        p.id === id && !p.tracks.some((t) => t.id === track.id)
          ? { ...p, tracks: [...p.tracks, track] }
          : p
      );
      const next = { ...prev, playlists };
      try { localStorage.setItem(KEY, JSON.stringify(next)); } catch {}
      return next;
    });
  }, []);

  const removeFromPlaylist = useCallback((id: string, trackId: string) => {
    setData((prev) => {
      const playlists = prev.playlists.map((p) =>
        p.id === id ? { ...p, tracks: p.tracks.filter((t) => t.id !== trackId) } : p
      );
      const next = { ...prev, playlists };
      try { localStorage.setItem(KEY, JSON.stringify(next)); } catch {}
      return next;
    });
  }, []);

  return {
    saved: data.saved,
    playlists: data.playlists,
    isSaved,
    toggleSaved,
    createPlaylist,
    deletePlaylist,
    addToPlaylist,
    removeFromPlaylist,
  };
}
